name: free_form_text
description: Library to implement painting styled, free form text to a Canvas.
version: 0.4.1
homepage: https://github.com/badger3512/free_form_text
issue_tracker: https://github.com/badger3512/free_form_text/issues
environment:
  sdk: '>=3.1.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  image: ^4.1.3
  path_provider: ^2.1.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1


# The following section is specific to Flutter packages.
flutter:

